# Generated by Django 5.2.7 on 2025-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('client', 'Client')], default='client', help_text="User's role in the system", max_length=20),
        ),
    ]
