# Generated by Django 5.2.7 on 2025-10-25 23:37

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0003_attachment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المؤشر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المؤشر')),
                ('metric_type', models.CharField(choices=[('completion_rate', 'معدل الإنجاز'), ('time_efficiency', 'كفاءة الوقت'), ('quality_score', 'نقاط الجودة'), ('collaboration', 'التعاون'), ('innovation', 'الابتكار')], max_length=50, verbose_name='نوع المؤشر')),
                ('target_value', models.FloatField(verbose_name='القيمة المستهدفة')),
                ('current_value', models.FloatField(default=0.0, verbose_name='القيمة الحالية')),
                ('unit', models.CharField(max_length=20, verbose_name='الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مؤشر أداء',
                'verbose_name_plural': 'مؤشرات الأداء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, verbose_name='وصف التقرير')),
                ('report_type', models.CharField(choices=[('productivity', 'تقرير الإنتاجية'), ('performance', 'تقرير الأداء'), ('time_tracking', 'تتبع الوقت'), ('cost_analysis', 'تحليل التكلفة'), ('team_performance', 'أداء الفريق')], max_length=50, verbose_name='نوع التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير تحليلي',
                'verbose_name_plural': 'التقارير التحليلية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الودجة')),
                ('widget_type', models.CharField(choices=[('chart', 'رسم بياني'), ('metric', 'مقياس'), ('table', 'جدول'), ('progress', 'شريط تقدم'), ('list', 'قائمة')], max_length=50, verbose_name='نوع الودجة')),
                ('data_source', models.CharField(max_length=100, verbose_name='مصدر البيانات')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموقع X')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموقع Y')),
                ('width', models.IntegerField(default=4, verbose_name='العرض')),
                ('height', models.IntegerField(default=3, verbose_name='الارتفاع')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ودجة لوحة التحكم',
                'verbose_name_plural': 'ودجات لوحة التحكم',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='المدة')),
                ('description', models.TextField(blank=True, verbose_name='وصف العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='المهمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تتبع الوقت',
                'verbose_name_plural': 'تتبع الوقت',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='المهام المكتملة')),
                ('tasks_created', models.IntegerField(default=0, verbose_name='المهام المنشأة')),
                ('time_spent', models.DurationField(default=datetime.timedelta, verbose_name='الوقت المستغرق')),
                ('productivity_score', models.FloatField(default=0.0, verbose_name='نقاط الإنتاجية')),
                ('comments_count', models.IntegerField(default=0, verbose_name='عدد التعليقات')),
                ('attachments_count', models.IntegerField(default=0, verbose_name='عدد المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='المشروع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقياس إنتاجية',
                'verbose_name_plural': 'مقاييس الإنتاجية',
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'project')},
            },
        ),
    ]
