# Generated by Django 5.2.7 on 2025-10-25 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم لوحة التحكم')),
                ('description', models.TextField(blank=True, verbose_name='وصف لوحة التحكم')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_public', models.BooleanField(default=False, verbose_name='عامة')),
                ('layout', models.JSONField(default=dict, verbose_name='تخطيط')),
                ('settings', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'لوحة تحكم',
                'verbose_name_plural': 'لوحات التحكم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المرشح')),
                ('filter_type', models.CharField(choices=[('date_range', 'نطاق تاريخ'), ('user', 'مستخدم'), ('project', 'مشروع'), ('status', 'حالة'), ('priority', 'أولوية')], max_length=20, verbose_name='نوع المرشح')),
                ('field_name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='القيمة الافتراضية')),
                ('options', models.JSONField(default=list, verbose_name='الخيارات')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='لوحة التحكم')),
            ],
            options={
                'verbose_name': 'مرشح لوحة التحكم',
                'verbose_name_plural': 'مرشحات لوحة التحكم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('chart', 'رسم بياني'), ('metric', 'مقياس'), ('table', 'جدول'), ('progress', 'شريط تقدم'), ('list', 'قائمة'), ('calendar', 'تقويم'), ('timeline', 'الخط الزمني'), ('gauge', 'مقياس'), ('pie', 'دائري'), ('bar', 'عمودي'), ('line', 'خطي')], max_length=50, verbose_name='نوع الودجة')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الودجة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الودجة')),
                ('data_source', models.CharField(max_length=100, verbose_name='مصدر البيانات')),
                ('data_config', models.JSONField(default=dict, verbose_name='إعدادات البيانات')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموقع X')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموقع Y')),
                ('width', models.IntegerField(default=4, verbose_name='العرض')),
                ('height', models.IntegerField(default=3, verbose_name='الارتفاع')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي')),
                ('refresh_interval', models.IntegerField(default=0, verbose_name='فترة التحديث (ثواني)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='لوحة التحكم')),
            ],
            options={
                'verbose_name': 'ودجة لوحة التحكم',
                'verbose_name_plural': 'ودجات لوحة التحكم',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('view', 'عرض فقط'), ('edit', 'تعديل'), ('admin', 'إدارة')], default='view', max_length=20, verbose_name='مستوى الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاركة')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='لوحة التحكم')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='مشارك بواسطة')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشارك مع')),
            ],
            options={
                'verbose_name': 'مشاركة لوحة التحكم',
                'verbose_name_plural': 'مشاركات لوحة التحكم',
                'ordering': ['-created_at'],
                'unique_together': {('dashboard', 'shared_with')},
            },
        ),
    ]
